/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.estoqueDAO;
import DAO.usuarioDAO;
import DTO.estoqueDTO;
import java.awt.Color;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author analu
 */
public class frmPrincipalVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmFuncionarioVIEW
     */
    public frmPrincipalVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtEndereco2 = new javax.swing.JTextField();
        txtEstoqueDiario = new javax.swing.JTextField();
        txtMediaDemanda = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        txtSomaDemandaAtendida = new javax.swing.JTextField();
        txtDemandaTotal = new javax.swing.JTextField();
        txtPrioridade = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        cbxPrioridade = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        jLabel4.setText("Demanda Total");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEstoqueDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstoqueDiarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtEstoqueDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 400, 30));
        getContentPane().add(txtMediaDemanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 400, 30));

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, -1, -1));
        getContentPane().add(txtSomaDemandaAtendida, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 400, 30));
        getContentPane().add(txtDemandaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 400, 30));
        getContentPane().add(txtPrioridade, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 134, -1));

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 100, -1));

        cbxPrioridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        getContentPane().add(cbxPrioridade, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 320, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/principal.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void restaurarDadosComboBoxPrioridade(){
        //COLOCAR O CODIGO DE BUSCA NO BANCO DE DADOS
        try {
            usuarioDAO objusuariodao = new usuarioDAO();
            //ResultSet rs = objusuariodao.listarPrioridade();
        } catch (Exception e) {
        }
    }
    
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        String mediaDemanda, estoqueDiario, demandaTotal, somaDemAtendido, prioridade;

        mediaDemanda = txtMediaDemanda.getText();
        estoqueDiario = txtEstoqueDiario.getText();
        demandaTotal = txtDemandaTotal.getText();
        somaDemAtendido = txtSomaDemandaAtendida.getText();
        prioridade = txtPrioridade.getText();

        estoqueDTO objestoqueDTO = new estoqueDTO();
        objestoqueDTO.setMedia_demanda(mediaDemanda);
        objestoqueDTO.setEstoque_diario(estoqueDiario);
        objestoqueDTO.setDemanda_total(demandaTotal);
        objestoqueDTO.setSoma_dem_atendido(somaDemAtendido);
        objestoqueDTO.setPrioridade(prioridade);

        estoqueDAO objestoqueDAO = new estoqueDAO();
        //chamar o metodo do funcionarioDAO
        objestoqueDAO.cadastrarDadosEstoque(objestoqueDTO);
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtEstoqueDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstoqueDiarioActionPerformed

    }//GEN-LAST:event_txtEstoqueDiarioActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // limpar campos
        txtDemandaTotal.setText("");
        txtEstoqueDiario.setText("");
        txtMediaDemanda.setText("");
        txtSomaDemandaAtendida.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipalVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cbxPrioridade;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDemandaTotal;
    private javax.swing.JTextField txtEndereco2;
    private javax.swing.JTextField txtEstoqueDiario;
    private javax.swing.JTextField txtMediaDemanda;
    private javax.swing.JTextField txtPrioridade;
    private javax.swing.JTextField txtSomaDemandaAtendida;
    // End of variables declaration//GEN-END:variables
}
