/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.estoqueDAO;
import DTO.estoqueDTO;

/**
 *
 * @author analu
 */
public class frmPrincipalVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmFuncionarioVIEW
     */
    public frmPrincipalVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtEndereco2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtEstoqueDiario = new javax.swing.JTextField();
        txtMediaDemanda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSomaDemandaAtendida = new javax.swing.JTextField();
        txtDemandaTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrioridade = new javax.swing.JTextField();

        jLabel4.setText("Demanda Total");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Estoque Diario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 89, -1));
        getContentPane().add(txtEstoqueDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 134, -1));
        getContentPane().add(txtMediaDemanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 134, -1));

        jLabel2.setText("Soma Demanda Atendida:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, -1));

        jLabel3.setText("Demanda Total");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        jLabel5.setText("Média Demanda");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));
        getContentPane().add(txtSomaDemandaAtendida, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 134, -1));
        getContentPane().add(txtDemandaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 134, -1));

        jLabel6.setText("Prioridade:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));
        getContentPane().add(txtPrioridade, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 134, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
        String mediaDemanda, estoqueDiario, demandaTotal, somaDemAtendido, prioridade;
        
        mediaDemanda = txtMediaDemanda.getText();
        estoqueDiario = txtEstoqueDiario.getText();
        demandaTotal = txtDemandaTotal.getText();
        somaDemAtendido = txtSomaDemandaAtendida.getText();
        prioridade = txtPrioridade.getText();
        
        estoqueDTO objestoqueDTO = new estoqueDTO();
        objestoqueDTO.setMedia_demanda(mediaDemanda);
        objestoqueDTO.setEstoque_diario(estoqueDiario);
        objestoqueDTO.setDemanda_total(demandaTotal);
        objestoqueDTO.setSoma_dem_atendido(somaDemAtendido);
        objestoqueDTO.setPrioridade(prioridade);
        
        estoqueDAO objestoqueDAO = new estoqueDAO();
        //chamar o metodo do funcionarioDAO
        objestoqueDAO.cadastrarDadosEstoque(objestoqueDTO);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipalVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtDemandaTotal;
    private javax.swing.JTextField txtEndereco2;
    private javax.swing.JTextField txtEstoqueDiario;
    private javax.swing.JTextField txtMediaDemanda;
    private javax.swing.JTextField txtPrioridade;
    private javax.swing.JTextField txtSomaDemandaAtendida;
    // End of variables declaration//GEN-END:variables
}
